// Offline Camera Calibration Tool
//
// Reads an H5 file (event + RGB), samples frames across the full recording,
// runs the auto-calibration grid search, and saves the result to a YAML file.
//
// Usage:
//   ./calibrate <data.h5> [-o calibration.yaml] [--side left|right]
//                         [--frames 20] [--wide]
//
// The resulting .yaml file is loaded by the tracker with --calib.

#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <cmath>
#include <algorithm>
#include <chrono>
#include <iomanip>

#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>

#include "rgb_reader.h"
#include "event.h"
#include "auto_calibrate.h"

// ---------------------------------------------------------------------------
//  Command-line parsing
// ---------------------------------------------------------------------------

struct CalibArgs {
    std::string h5path;
    std::string outpath = "calibration.yaml";
    std::string side    = "left";
    int         nFrames = 20;       // how many frames to sample
    bool        wide    = false;    // wider search (no intrinsics guess)
    bool        preview = false;    // show result overlay
};

static CalibArgs parseArgs(int argc, char** argv) {
    CalibArgs a;
    if (argc < 2) {
        std::cerr << "Usage: " << argv[0]
                  << " <data.h5> [-o calibration.yaml] [--side left|right]"
                  << " [--frames 20] [--wide] [--preview]\n";
        std::exit(1);
    }
    a.h5path = argv[1];
    for (int i = 2; i < argc; ++i) {
        std::string arg = argv[i];
        if ((arg == "-o" || arg == "--output") && i+1 < argc) a.outpath = argv[++i];
        else if (arg == "--side" && i+1 < argc) a.side = argv[++i];
        else if (arg == "--frames" && i+1 < argc) a.nFrames = std::stoi(argv[++i]);
        else if (arg == "--wide") a.wide = true;
        else if (arg == "--preview") a.preview = true;
    }
    return a;
}

// ---------------------------------------------------------------------------
//  Save / preview
// ---------------------------------------------------------------------------

static bool saveCalibration(const std::string& path, const CalibResult& cal,
                            const std::string& h5path) {
    std::ofstream f(path);
    if (!f.is_open()) {
        std::cerr << "Error: cannot write to " << path << "\n";
        return false;
    }
    f << "# Camera calibration (event ↔ RGB)\n"
      << "# Generated by: calibrate tool\n"
      << "# Source file : " << h5path << "\n"
      << "#\n"
      << "# Transform: u_evt = sx * u_rgb + ox\n"
      << "#            v_evt = sy * v_rgb + oy\n"
      << "#\n"
      << std::fixed << std::setprecision(6)
      << "sx: " << cal.sx << "\n"
      << "sy: " << cal.sy << "\n"
      << "ox: " << cal.ox << "\n"
      << "oy: " << cal.oy << "\n"
      << "score: " << cal.score << "\n";
    f.close();
    return true;
}

// Show a visual overlay of the calibration result
static void showPreview(const cv::Mat& rgb, const cv::Mat& evt_edges,
                        const CalibResult& cal) {
    cv::Mat gray, rgb_edges;
    cv::cvtColor(rgb, gray, cv::COLOR_BGR2GRAY);
    cv::Canny(gray, rgb_edges, 40, 120);

    // Warp event edges into RGB space and overlay
    cv::Mat vis = rgb.clone();
    int ew = evt_edges.cols, eh = evt_edges.rows;
    int rw = rgb.cols, rh = rgb.rows;

    for (int ey = 0; ey < eh; ++ey) {
        // Inverse: ry = (ey - oy) / sy
        int ry = (int)std::round((ey - cal.oy) / cal.sy);
        if (ry < 0 || ry >= rh) continue;
        for (int ex = 0; ex < ew; ++ex) {
            if (evt_edges.at<uchar>(ey, ex) == 0) continue;
            int rx = (int)std::round((ex - cal.ox) / cal.sx);
            if (rx < 0 || rx >= rw) continue;

            // Green if event edge hits an RGB edge, red if it doesn't
            bool hit = rgb_edges.at<uchar>(ry, rx) > 0;
            auto& px = vis.at<cv::Vec3b>(ry, rx);
            if (hit) px = {0, 255, 0};
            else     px = {0, 0, 200};
        }
    }

    char buf[128];
    snprintf(buf, sizeof(buf), "Calibration: sx=%.4f sy=%.4f ox=%.1f oy=%.1f  score=%d%%",
             cal.sx, cal.sy, cal.ox, cal.oy, (int)(cal.score * 100));
    cv::putText(vis, buf, {10, 30}, cv::FONT_HERSHEY_SIMPLEX, 0.7, {255,255,255}, 2);
    cv::putText(vis, "Green=aligned  Red=misaligned  Press any key to close",
                {10, 60}, cv::FONT_HERSHEY_SIMPLEX, 0.5, {200,200,200}, 1);

    cv::namedWindow("Calibration Preview", cv::WINDOW_NORMAL);
    cv::resizeWindow("Calibration Preview", 1280, 720);
    cv::imshow("Calibration Preview", vis);
    cv::waitKey(0);
    cv::destroyAllWindows();
}

// ---------------------------------------------------------------------------
//  Main
// ---------------------------------------------------------------------------

int main(int argc, char** argv) {
    CalibArgs args = parseArgs(argc, argv);

    std::cout << "\n============================================\n"
              << "  Camera Calibration Tool\n"
              << "============================================\n\n";

    // Open data sources
    RGBReader reader;
    if (!reader.openH5(args.h5path)) {
        std::cerr << "Failed to open H5 for RGB: " << args.h5path << "\n";
        return 1;
    }
    H5EventReader eventReader;
    if (!eventReader.open(args.h5path, args.side)) {
        std::cerr << "Failed to open H5 for events: " << args.h5path << "\n";
        return 1;
    }

    int totalFrames = reader.numFrames();
    std::cout << "  RGB : " << totalFrames << " frames @ " << reader.fps()
              << " fps  (" << reader.width() << "x" << reader.height() << ")\n"
              << "  Evt : " << eventReader.totalEvents() << " events  "
              << eventReader.width() << "x" << eventReader.height()
              << "  (" << args.side << ")\n"
              << "  Sampling " << args.nFrames << " frames for calibration\n\n";

    // Sample frames evenly across the recording
    int n = std::min(args.nFrames, totalFrames);
    std::vector<cv::Mat> rgb_edges_vec, evt_edges_vec;
    cv::Mat lastRgb, lastEvtEdges;

    std::cout << "  Extracting edge pairs...\n";
    for (int i = 0; i < n; i++) {
        // Spread frames across 10%-90% of the recording to avoid start/end junk
        double frac = 0.1 + 0.8 * (double)i / std::max(1, n - 1);
        int fi = std::min(totalFrames - 1, (int)(totalFrames * frac));
        double t = reader.startTime() + fi / reader.fps();

        cv::Mat frm;
        if (!reader.getFrame(t, frm) || frm.empty()) continue;
        cv::Mat gray, edges;
        cv::cvtColor(frm, gray, cv::COLOR_BGR2GRAY);
        cv::Canny(gray, edges, 40, 120);

        EventBatch evts;
        double evt_win = 0.015;  // 15ms window around the frame
        eventReader.readBatch(std::max(0.0, t - evt_win), evt_win * 2, evts);
        cv::Mat evt_edges = buildEventEdges(evts,
            eventReader.width(), eventReader.height());

        if (!edges.empty() && !evt_edges.empty()) {
            rgb_edges_vec.push_back(edges);
            evt_edges_vec.push_back(evt_edges);
            lastRgb = frm.clone();
            lastEvtEdges = evt_edges.clone();
        }

        if ((i + 1) % 5 == 0 || i == n - 1)
            std::cout << "    " << (i + 1) << "/" << n << " frames\n";
    }

    if (rgb_edges_vec.empty()) {
        std::cerr << "Error: no usable frame pairs found.\n";
        return 1;
    }
    std::cout << "  Got " << rgb_edges_vec.size() << " usable edge pairs.\n\n";

    // Choose initial guess
    double init_sx, init_sy, init_ox, init_oy;
    if (args.wide) {
        // No prior knowledge — camera-agnostic defaults
        init_sx = 0.85;  init_sy = 0.85;
        init_ox = 0.0;   init_oy = 0.0;
        std::cout << "  Using WIDE search (no intrinsics, camera-agnostic)\n";
    } else {
        // Use M3ED falcon intrinsics as a reasonable starting point
        double fx_e = 1034.86, fy_e = 1033.48, cx_e = 629.70, cy_e = 357.60;
        double fx_r = 1268.56, fy_r = 1267.35, cx_r = 649.37, cy_r = 359.94;
        init_sx = fx_e / fx_r;
        init_sy = fy_e / fy_r;
        init_ox = cx_e - cx_r * init_sx;
        init_oy = cy_e - cy_r * init_sy;
        std::cout << "  Using M3ED intrinsics as initial guess\n"
                  << "  (use --wide if you have different cameras)\n";
    }

    std::cout << "  Initial guess: sx=" << std::fixed << std::setprecision(4)
              << init_sx << " sy=" << init_sy
              << " ox=" << std::setprecision(1) << init_ox
              << " oy=" << init_oy << "\n\n";

    // Run the calibration
    auto t_start = std::chrono::steady_clock::now();

    CalibResult cal = autoCalibrate(
        rgb_edges_vec, evt_edges_vec,
        init_sx, init_sy, init_ox, init_oy,
        args.wide);

    auto t_end = std::chrono::steady_clock::now();
    double elapsed = std::chrono::duration<double>(t_end - t_start).count();

    std::cout << "\n  ============ RESULT ============\n"
              << "    sx = " << std::setprecision(6) << cal.sx << "\n"
              << "    sy = " << cal.sy << "\n"
              << "    ox = " << std::setprecision(2) << cal.ox << "\n"
              << "    oy = " << cal.oy << "\n"
              << "    Edge overlap: " << (int)(cal.score * 100) << "%\n"
              << "    Time: " << std::setprecision(1) << elapsed << "s\n"
              << "  ================================\n\n";

    // Save
    if (saveCalibration(args.outpath, cal, args.h5path)) {
        std::cout << "  Saved to: " << args.outpath << "\n";
        std::cout << "  Use with tracker:  ./tracker <data.h5> --calib " << args.outpath << "\n\n";
    }

    // Optional preview
    if (args.preview && !lastRgb.empty() && !lastEvtEdges.empty()) {
        showPreview(lastRgb, lastEvtEdges, cal);
    }

    return 0;
}
